from dotenv import load_dotenv
import os

load_dotenv()

ENVIRONMENT = os.getenv("ENVIRONMENT")
NOTIFICATION_MODE = os.getenv("NOTIFICATION_MODE")

VN30_DISCORD_URL = os.getenv("VN30_DISCORD_URL")

DISCORD_POSITIVE_COLOR = 43127
DISCORD_NEGATIVE_COLOR = 15859772
DISCORD_NEUTRAL_COLOR = 0

EMAIL_SENDER = os.getenv("EMAIL_SENDER")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
EMAIL_RECEIVERS = os.getenv("EMAIL_RECEIVERS")

EMAIL_POSITIVE_COLOR = "#00FF00"
EMAIL_NEGATIVE_COLOR = "#FF0000"
EMAIL_NEUTRAL_COLOR = "#000000"

ACTION_BUY = "BUY"
ACTION_SELL = "SELL"

TYPE_STOCK = "stock"
TYPE_DERIVATIVE = "derivative"
